apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "foobar files"
        files:
          - /
        image: "alpine:3.15"
        cmd:
          - "ls"
        args:
         - "-la"
         - "/keptn"
