apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "foobar files"
        files:
          - /charts
        image: "alpine/helm:3.7.2"
        cmd:
          - helm
        args:
          - "install"
          - "-n"
          - "$(PROJECT)-$(STAGE)"
          - "--create-namespace"
          - "$(SERVICE)"
          - "/keptn/charts/$(SERVICE).tgz"
          - "--set"
          - "image=$(IMAGE)"
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
          - name: IMAGE
            value: "$.data.configurationChange.values.image"
            valueFrom: event

  - name: "Run tests using locust"
    events:
      - name: "sh.keptn.event.je-test.triggered"
    tasks:
      - name: "Run locust"
        files:
          - locust/basic.py
          - locust/load.py
          - locust/locust.conf
        image: "locustio/locust"
        cmd:
          - locust
        args:
          - '--config'
          - /keptn/locust/locust.conf
          - '-f'
          - /keptn/locust/basic.py
          - '--host'
          - helloservice.$(PROJECT)-$(STAGE)
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
