apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "list files"
        files:
          - /
        image: "alpine/helm:3.7.2"
        cmd:
          - ls

  - name: "Run locust"
    events:
      - name: "sh.keptn.event.je-test.triggered"
    tasks:
      - name: "Run locust tests"
        files:
          - locust/basic.py
          - locust/load.py
          - locust/locust.conf
        image: "locustio/locust:2.5.1"
        cmd:
          - locust
        args:
          - '--config'
          - /keptn/locust/locust.conf
          - '-f'
          - /keptn/locust/load.py
          - '--host'
          - $(HOST)
        env:
          - name: HOST
            value: "$.data.deployment.deploymentURIsLocal[0]"
            valueFrom: event
          - name: TEST_STRATEGY
            value: "$.data.test.testStrategy"
            valueFrom: event

