apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "foobar files"
        files:
          - /charts
        image: "alpine/helm:3.7.2"
        cmd:
          - helm
        args:
          - "install"
          - "-n"
          - "$(PROJECT)-$(STAGE)"
          - "--create-namespace"
          - "$(SERVICE)"
          - "/keptn/charts/$(SERVICE).tgz"
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
