apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "foobar files"
        files:
          - /charts
        image: "alpine/helm:3.7.2"
        cmd:
          - ls
        args:
          - "-latr"
          - "/keptn"
